apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "cc-service-search.fullname" . }}-cc-service-search-ingress
spec:

  rules:
  - host: {{ .Values.ccServiceSearch.hostname }}
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: {{ include "cc-service-search.fullname" . }}-cc-service-search
            port:
              number: 8000
