apiVersion: v1
kind: Secret
metadata:
  name: ccsearch-dbaccess
data:
  db_user: {{ .Values.ccServiceSearch.db_user | b64enc }}
  db_password: {{ .Values.ccServiceSearch.db_password | b64enc }}
---
apiVersion: v1
kind: Secret
metadata:
  name: ccsearch-dbaccess-admin
data:
  admin_db_password: {{ .Values.ccServiceSearch.admin_db_password | b64enc }}
---
apiVersion: v1
kind: Secret
metadata:
  name: opensearch-initial-admin-pass
data:
  OPENSEARCH_INITIAL_ADMIN_PASSWORD: {{ .Values.ccServiceSearch.admin_db_password | b64enc }}

